### ISSUE TITLE
retention not works

### ISSUE THREAD

**Issue by and-cesbo** [runcitrus/fugo#4]
configured 3 days retention:

```yaml
...
retention:
  period: 3d
  interval: 1h
```

but we have records older than 3 days:

```
# curl -sG 'http://127.0.0.1:2221/api/query/nginx-access?limit=1&time__until=3d2h' 
{"_cursor":"0000000000000463","time":1744260089000,...}
```
